# Generated by Django 3.0.8 on 2020-08-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_destination_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('pack', models.CharField(max_length=50)),
                ('discount', models.BooleanField(default=False)),
            ],
        ),
    ]
