# Generated by Django 3.0.8 on 2020-08-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_specialoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialoffer',
            old_name='discount',
            new_name='offer',
        ),
    ]
