# Generated by Django 3.0.8 on 2020-08-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200807_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
