# Generated by Django 3.0.8 on 2020-08-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc1',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
