# Generated by Django 3.0.8 on 2020-08-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200809_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='pack',
        ),
    ]
