# Generated by Django 3.0.8 on 2020-08-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200810_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayitenary',
            name='day',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='day',
        ),
        migrations.AddField(
            model_name='dayitenary',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Packages'),
        ),
    ]
