# Generated by Django 3.0.8 on 2020-08-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200810_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayitenary',
            name='name',
        ),
        migrations.AlterField(
            model_name='dayitenary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
