# Generated by Django 3.0.8 on 2020-08-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200810_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayItenary',
        ),
    ]
