# Generated by Django 3.0.8 on 2020-08-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_delete_dayitenary'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='day_1',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_10',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_2',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_3',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_4',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_5',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_6',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_7',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_8',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_9',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
