# Generated by Django 3.0.8 on 2020-08-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200810_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='day_10_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_1_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_2_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_3_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_4_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_5_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_6_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_7_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_8_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='packages',
            name='day_9_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
