# Generated by Django 3.0.8 on 2020-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200810_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='day_1',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_10',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_10_img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_1_img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_2',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_2_img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_3',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_3_img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_4',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_4_img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_5',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_5_img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_6',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_6_img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_7',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_7_img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_8',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_8_img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_9',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='day_9_img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
    ]
