# Generated by Django 3.0.8 on 2020-08-10 21:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=django.contrib.auth.models.AbstractUser.get_full_name),
        ),
    ]
