# Generated by Django 3.0.8 on 2020-08-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20200811_0321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
