# Generated by Django 3.0.8 on 2020-08-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20200811_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.CharField(max_length=500, null=True, verbose_name='auth.User.get_first_name'),
        ),
    ]
