# Generated by Django 3.0.8 on 2020-08-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20200811_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
