# Generated by Django 3.0.8 on 2020-08-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_contact_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviewer_img',
            field=models.ImageField(blank=True, default='testimonial1.jpg', null=True, upload_to='pics'),
        ),
    ]
