# Generated by Django 3.0.8 on 2020-08-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20200812_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
