# Generated by Django 3.0.8 on 2020-08-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.CharField(max_length=1000),
        ),
    ]
