# Generated by Django 3.0.8 on 2020-08-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200808_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
